# Generated by Django 3.0.3 on 2020-02-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_asignaturas_docente_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
    ]
