# Generated by Django 3.0.3 on 2020-02-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Estudiante', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
